"""Generate supabase/seed.sql (students, courses, course faculty) from the data in index.html.

The portal keeps its student list and timetable in index.html; run this after changing either so the
database matches:

    python scripts/generate_seed.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
html = (ROOT / "index.html").read_text(encoding="utf-8")


def sql(value):
    return "'" + str(value).replace("'", "''") + "'"


# Students: lines like "0001/62|AASTHA YADAV" inside ROSTER_TEXT
roster_block = re.search(r"const ROSTER_TEXT = `(.*?)`;", html, re.S).group(1)
students = [line.split("|", 1) for line in roster_block.strip().splitlines()]

# Courses: lines like  "Name": { profs: [...], hall: "...", credits: 3 }
courses_block = re.search(r"const COURSES = \{(.*?)\n\};", html, re.S).group(1)
courses = []
for m in re.finditer(r'^\s*("(?:[^"\\]|\\.)*"): \{ profs: (\[.*?\]), hall: ("(?:[^"\\]|\\.)*"), credits: ([\d.]+) \}', courses_block, re.M):
    courses.append((json.loads(m.group(1)), json.loads(m.group(2)), json.loads(m.group(3)), float(m.group(4))))

assert students and courses, "Could not find the student list or courses in index.html"

out = ["-- Generated by scripts/generate_seed.py from index.html. Do not edit by hand.", ""]
out.append("insert into public.students (reg, name, batch) values")
out.append(",\n".join(f"  ({sql(reg)}, {sql(name)}, {sql(reg.split('/')[1])})" for reg, name in students))
out.append("on conflict (reg) do update set name = excluded.name, batch = excluded.batch;")
out.append("")
out.append("insert into public.courses (name, credits, min_attendance_pct, hall) values")
out.append(",\n".join(
    f"  ({sql(name)}, {credits:g}, {75 if credits == 1.5 else 80}, {sql(hall)})" for name, _, hall, credits in courses))
out.append("on conflict (name) do update set credits = excluded.credits, min_attendance_pct = excluded.min_attendance_pct, hall = excluded.hall;")
out.append("")
out.append("insert into public.course_faculty (course, faculty_name) values")
out.append(",\n".join(f"  ({sql(name)}, {sql(prof)})" for name, profs, _, _ in courses for prof in profs))
out.append("on conflict do nothing;")
out.append("")

(ROOT / "supabase" / "seed.sql").write_text("\n".join(out), encoding="utf-8", newline="\n")
print(f"Wrote supabase/seed.sql: {len(students)} students, {len(courses)} courses")
